In [2]:
import cv2 as cv
import numpy as np

In [ ]:
# read and show image

In [ ]:
img = cv.imread("dog1.jpg")
cv.imshow("dog",img)
cv.waitKey(0)
cv.destroyAllWindows()

In [ ]:
#image read and resize

In [ ]:
imgSlide = cv.imread("img.jpg")
imgResize = cv.resize(imgSlide,(500,300))
cv.imshow("slide",imgResize)
cv.waitKey(0)
cv.destroyAllWindows()

In [ ]:
# multiple images in single frames veritcal and vorizontal

In [ ]:
imgD = cv.imread("img.jpg")
imgD1 = cv.imread("dog.jpg")
resize = cv.resize(imgD,(200,200))
resize1 = cv.resize(imgD1,(200,200))

horiz = np.hstack([resize,resize1,resize,resize1])
vertical = np.vstack([horiz,horiz,horiz])
cv.imshow("img",vertical)
cv.waitKey(0)
cv.destroyAllWindows()


In [ ]:
# slide the images

In [ ]:
imgList = ["dog.jpg","dog1.jpg","img.jpg"]
for i in imgList:
    img = cv.imread(i,1)
    resize = cv.resize(img,(500,300))
    cv.imshow("Manish",resize)
    cv.waitKey(0)
    
cv.destroyAllWindows()    

In [ ]:
# overlap the images

In [ ]:
img = cv.imread("dog.jpg")
img1 = cv.imread("dog1.jpg")

res = cv.resize(img,(400,300))
res1 = cv.resize(img1,(400,300))

overLap = cv.addWeighted(res,2,res1,0.7,4)
cv.imshow("overlap",overLap)
cv.waitKey(0)
cv.destroyAllWindows()

In [ ]:
#edge detection

In [ ]:
img = cv.imread("dog.jpg")
res = cv.resize(img,(400,300))
newImg = cv.Canny(res,100,70)
cv.imshow("Img",newImg)
cv.waitKey(0)
cv.destroyAllWindows()


In [ ]:
# blur the images

In [ ]:
img = cv.imread("dog2.jpg",1)
if img is None:
    print("no image")
else:
    res = cv.resize(img,(300,200))
#     newImg = cv.medianBlur(res,5)
    newImg = cv.bilateralFilter(res,12,100,100)
    cv.imshow("Img",newImg)
    cv.waitKey(0)
    cv.destroyAllWindows()

In [ ]:
# save images

In [ ]:
listG=[]
dogList = ["dog.jpg","dog1.jpg","dog2.jpg"]
for i in dogList:
    if i is None:
        print("No Image")
    else:
        read = cv.imread(i)
        resize = cv.resize(read,(300,200))
        listG.append(resize)
    
horiz = np.hstack(listG)
cv.imwrite("allDog.jpg",horiz)
cv.imshow("window",horiz)
cv.waitKey(0)
cv.destroyAllWindows()

In [ ]:
# capture video from webcam

In [6]:
video = cv.VideoCapture(0)

while video.isOpened():
    ret,frame = video.read()
    if ret == True:
        cv.imshow("opne",frame)
        if cv.waitKey(25) & 0xff == ord("p"):
            break
    else:
        break
   
        
video.release()
cv.destroyAllWindows()

In [ ]:
# Read video from the file

In [8]:
cap = cv.VideoCapture("AWS-Solutions.mp4")
while cap.isOpened():
    ret, fram = cap.read()
    print(ret,"-----",fram,"-----",fram.shape)
    if ret == True:
        fram =cv.resize(fram,(600,500))
        cv.imshow("web",fram)
        if cv.waitKey(25) & 0xff == ord('p'):
            break   
    else:
        break
        
cap.release()
cv.destroyAllWindows()

True ----- [[[210 149  19]
  [210 149  19]
  [210 149  19]
  ...
  [213 150  20]
  [213 150  20]
  [213 150  20]]

 [[210 149  19]
  [210 149  19]
  [210 149  19]
  ...
  [213 150  20]
  [213 150  20]
  [213 150  20]]

 [[210 149  19]
  [210 149  19]
  [210 149  19]
  ...
  [213 150  20]
  [213 150  20]
  [213 150  20]]

 ...

 [[189 137  21]
  [189 137  21]
  [189 137  21]
  ...
  [169 121  18]
  [168 120  17]
  [167 119  16]]

 [[189 137  21]
  [189 137  21]
  [189 137  21]
  ...
  [169 121  18]
  [168 120  17]
  [167 119  16]]

 [[189 137  21]
  [189 137  21]
  [189 137  21]
  ...
  [169 121  18]
  [168 120  17]
  [167 119  16]]] ----- (720, 1280, 3)
True ----- [[[210 149  19]
  [210 149  19]
  [210 149  19]
  ...
  [213 150  20]
  [213 150  20]
  [213 150  20]]

 [[210 149  19]
  [210 149  19]
  [210 149  19]
  ...
  [213 150  20]
  [213 150  20]
  [213 150  20]]

 [[210 149  19]
  [210 149  19]
  [210 149  19]
  ...
  [213 150  20]
  [213 150  20]
  [213 150  20]]

 ...

 [[189 13

True ----- [[[210 149  19]
  [210 149  19]
  [210 149  19]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[210 149  19]
  [210 149  19]
  [210 149  19]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[210 149  19]
  [210 149  19]
  [210 149  19]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[189 137  21]
  [189 137  21]
  [189 137  21]
  ...
  [169 121  18]
  [168 120  17]
  [167 119  16]]

 [[189 137  21]
  [189 137  21]
  [189 137  21]
  ...
  [169 121  18]
  [168 120  17]
  [167 119  16]]

 [[189 137  21]
  [189 137  21]
  [189 137  21]
  ...
  [169 121  18]
  [168 120  17]
  [167 119  16]]] ----- (720, 1280, 3)
True ----- [[[210 149  19]
  [210 149  19]
  [210 149  19]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[210 149  19]
  [210 149  19]
  [210 149  19]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[210 149  19]
  [210 149  19]
  [210 149  19]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[189 13

True ----- [[[210 149  19]
  [210 149  19]
  [210 149  19]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[210 149  19]
  [210 149  19]
  [210 149  19]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[210 149  19]
  [210 149  19]
  [210 149  19]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[189 137  21]
  [189 137  21]
  [189 137  21]
  ...
  [169 121  18]
  [168 120  17]
  [167 119  16]]

 [[189 137  21]
  [189 137  21]
  [189 137  21]
  ...
  [169 121  18]
  [168 120  17]
  [167 119  16]]

 [[189 137  21]
  [189 137  21]
  [189 137  21]
  ...
  [169 121  18]
  [168 120  17]
  [167 119  16]]] ----- (720, 1280, 3)
True ----- [[[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[189 13

True ----- [[[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]] ----- (720, 1280, 3)
True ----- [[[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 13

True ----- [[[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]] ----- (720, 1280, 3)
True ----- [[[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 13

True ----- [[[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]] ----- (720, 1280, 3)
True ----- [[[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 13

True ----- [[[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]] ----- (720, 1280, 3)
True ----- [[[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 13

True ----- [[[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]] ----- (720, 1280, 3)
True ----- [[[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 13

True ----- [[[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]] ----- (720, 1280, 3)
True ----- [[[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 13

True ----- [[[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]] ----- (720, 1280, 3)
True ----- [[[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 13

True ----- [[[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]] ----- (720, 1280, 3)
True ----- [[[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 13

True ----- [[[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]] ----- (720, 1280, 3)
True ----- [[[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 13

True ----- [[[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 122  17]
  [170 121  16]
  [168 119  14]]] ----- (720, 1280, 3)
True ----- [[[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[211 150  20]
  [211 150  20]
  [211 150  20]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 13

True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]] ----- (720, 1280, 3)
True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 13

True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]] ----- (720, 1280, 3)
True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 13

True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]] ----- (720, 1280, 3)
True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 13

True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]] ----- (720, 1280, 3)
True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 13

True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]] ----- (720, 1280, 3)
True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 13

True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]] ----- (720, 1280, 3)
True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 13

True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]] ----- (720, 1280, 3)
True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 13

True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]] ----- (720, 1280, 3)
True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 13

True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [171 121  18]
  [170 120  17]
  [169 119  16]]] ----- (720, 1280, 3)
True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 13

True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [169 122  17]
  [167 120  15]
  [166 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [169 122  17]
  [167 120  15]
  [166 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [169 122  17]
  [167 120  15]
  [166 119  14]]] ----- (720, 1280, 3)
True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 13

True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [169 122  17]
  [167 120  15]
  [166 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [169 122  17]
  [167 120  15]
  [166 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [169 122  17]
  [167 120  15]
  [166 119  14]]] ----- (720, 1280, 3)
True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 13

True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [169 122  17]
  [167 120  15]
  [166 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [169 122  17]
  [167 120  15]
  [166 119  14]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [169 122  17]
  [167 120  15]
  [166 119  14]]] ----- (720, 1280, 3)
True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 13

True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [169 121  18]
  [167 119  16]
  [166 118  15]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [169 121  18]
  [167 119  16]
  [166 118  15]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [169 121  18]
  [167 119  16]
  [166 118  15]]] ----- (720, 1280, 3)
True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 13

True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [169 121  18]
  [167 119  16]
  [166 118  15]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [169 121  18]
  [167 119  16]
  [166 118  15]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [169 121  18]
  [167 119  16]
  [166 118  15]]] ----- (720, 1280, 3)
True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 13

True ----- [[[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 [[213 152  22]
  [213 152  22]
  [213 152  22]
  ...
  [211 150  20]
  [211 150  20]
  [211 150  20]]

 ...

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [169 121  18]
  [167 119  16]
  [166 118  15]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [169 121  18]
  [167 119  16]
  [166 118  15]]

 [[188 136  20]
  [188 136  20]
  [188 136  20]
  ...
  [169 121  18]
  [167 119  16]
  [166 118  15]]] ----- (720, 1280, 3)


In [9]:
# fast motion and slow motion

In [14]:
vid = cv.VideoCapture(0)
while vid.isOpened():
    r,frame =vid.read()
    if r == True:
        frame = cv.resize(frame,(500,400))
        cv.imshow("motion",frame)
        if cv.waitKey(8) & 0xff == ord("p"):
            break
            
    else:
        break
        
vid.release()
cv.destroyAllWindows()